# lightning==2.3.0.dev0
seed_everything: 1
trainer:
  accelerator: gpu
  devices: 1
  strategy: auto
  max_epochs: 50
  use_distributed_sampler: false
  limit_train_batches: 100
  log_every_n_steps: 1
  check_val_every_n_epoch: 1
  default_root_dir: ./results
  accumulate_grad_batches: 1
  gradient_clip_val: 0.5
model:
  forecaster:
    class_path: probts.model.forecaster.prob_forecaster.LSG_VAE_Forecaster.LSG_VAEModel
    init_args:
      d_model: 128
      d_ff: 256
      e_layers: 1
      dropout: 0.1
      activation: relu
      n_heads: 4
      factor: 3
      patch_len: 24
      multistep: true
      dynamic_dim: 128
      hidden_layers: 3
      hidden_dim: 256
      weight_beta: 0.01
      sample_schedule: 20
      init_koopman: dynamic
  num_samples: 100
  learning_rate: 0.001
  quantiles_num: 20
data:
  data_manager:
    class_path: probts.data.data_manager.DataManager
    init_args:
      split_val: true
      scaler: standard # identity, standard, temporal
  batch_size: 64
  test_batch_size: 32
  num_workers: 8
